kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: gdx-agreements-tracker-api-postgres-deployment-configuration
  resourceVersion: "v1.0.0"
  annotations:
    openshift.io/display-name: Deployment GDX agreements tracker postgres database configuration.
    description: Deployment for GDX agreements tracker postgres database.
    tags: pmo,api,gdx,agreements-tracker,postgres
parameters:
  - name: APP_NAME
    displayName: "App Name"
    description: "The name of the application (grouped)."
    required: true
    value: "gdx-agreements-tracker"
  - name: ROLE_NAME
    displayName: "Component Name"
    description: "The name of the application role."
    required: true
    value: "api"
  - name: PROJECT_NAMESPACE
    displayName: "OpenShift Project Namespace"
    description: "The namespace of the OpenShift project containing the application."
    required: true
    value: "acd38d"
  - name: ENV_NAME
    displayName: "Environment name"
    description: "The name for this environment [dev, test, prod, tools]"
    required: true
    value: "dev"

  - name: POSTGRES_REGULAR_USER
    displayName: "POSTGRES_USER"
    description: "The database regular account name."
    value: "pmouser"
  - name: POSTGRES_REGULAR_USER_PASSWORD
    displayName: "POSTGRES_USER_PASSWORD"
    description: "Regular user password."
    value: "OMGyouMUSTchangeMEbeforeDEPLOY"
  - name: POSTGRES_DB
    displayName: "POSTGRES_DB"
    description: "Starting database name."
    value: "pmodb"
  - name: POSTGRES_ROOT_USER
    displayName: "POSTGRES_USER"
    description: "The database superuser account name."
    value: "postgres"
  - name: POSTGRES_ROOT_PASSWORD
    displayName: "POSTGRES_PASSWORD"
    description: "Superuser password."
    value: "OMGyouMUSTchangeMEbeforeDEPLOY"

objects:
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: 0-${APP_NAME}-${ROLE_NAME}-postgres-env-config
      namespace: ${PROJECT_NAMESPACE}-${ENV_NAME}
      annotations:
        description: "Database client configuration"
      labels:
        name: 0-${APP_NAME}-${ROLE_NAME}-postgres-env-config
        app: ${APP_NAME}
        env: ${ENV_NAME}
    type: Opaque
    data:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_ROOT_USER}
      POSTGRES_REGULAR_USER: ${POSTGRES_REGULAR_USER}

  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: 0-${APP_NAME}-${ROLE_NAME}-postgres-file-config
      namespace: ${PROJECT_NAMESPACE}-${ENV_NAME}
      annotations:
        description: "Database client configuration"
      labels:
        name: 0-${APP_NAME}-${ROLE_NAME}-postgres-file-config
        app: ${APP_NAME}
        env: ${ENV_NAME}
    type: Opaque
    data:
      postgresql.conf: |
        listen_addresses = '*'
        max_connections = 100			# (change requires restart)
        shared_buffers = 1024MB			# min 128kB
        dynamic_shared_memory_type = posix	# the default is the first option
        max_wal_size = 1GB
        min_wal_size = 80MB
        log_timezone = 'UTC'
        datestyle = 'iso, mdy'
        timezone = 'UTC'
        lc_messages = 'en_US.utf8'			# locale for system error message
        lc_monetary = 'en_US.utf8'			# locale for monetary formatting
        lc_numeric = 'en_US.utf8'			# locale for number formatting
        lc_time = 'en_US.utf8'				# locale for time formatting
        default_text_search_config = 'pg_catalog.english'

  - kind: Secret
    apiVersion: v1
    metadata:
      name: 0-${APP_NAME}-${ROLE_NAME}-postgres-secrets
      namespace: ${PROJECT_NAMESPACE}-${ENV_NAME}
      annotations:
        description: "PostgreSQL secrets"
      labels:
        name: 0-${APP_NAME}-${ROLE_NAME}-postgres-secrets
        app: ${APP_NAME}
        env: ${ENV_NAME}
    type: Opaque
    stringData:
      POSTGRES_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
      POSTGRES_REGULAR_USER_PASSWORD: ${POSTGRES_REGULAR_USER_PASSWORD}
